version: '1.0'
services:
  efilen-webdav:
    image: efilen-webdav:latest
    container_name: efilen-webdav
    ports:
      - "${PORT:-8888}:8888"
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8888}
      - HTTPS=${HTTPS:-false}
      - AUTH_MODE=${AUTH_MODE:-basic}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 